"""Add application table and relationship to user and venue

Revision ID: 13dd8010dddc
Revises: 60e48ec39040
Create Date: 2024-08-26 03:34:41.022966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dd8010dddc'
down_revision: Union[str, None] = '60e48ec39040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['vid'], ['venue.vid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
