"""Add venue table

Revision ID: 60e48ec39040
Revises: dd36ad7e2236
Create Date: 2024-08-26 03:23:50.119013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60e48ec39040"
down_revision: Union[str, None] = "dd36ad7e2236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venue",
        sa.Column("vid", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("vid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("venue")
    # ### end Alembic commands ###
